// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZEyspaFb4swXkxvoM1MRJPv-7TRX8A0o',
    appId: '1:453820398714:web:595656e6c9fe4d3fa1cfc3',
    messagingSenderId: '453820398714',
    projectId: 'skydreamer-skywalker',
    authDomain: 'skydreamer-skywalker.firebaseapp.com',
    storageBucket: 'skydreamer-skywalker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5DrITlT8zKdZ2BgUh1pGdPsgAzcMBsFo',
    appId: '1:453820398714:android:36cf1b781497b4aca1cfc3',
    messagingSenderId: '453820398714',
    projectId: 'skydreamer-skywalker',
    storageBucket: 'skydreamer-skywalker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApBbN5M8u77tvgRkKKrEP5-SziQb0CEOM',
    appId: '1:453820398714:ios:021cabc9e38ba807a1cfc3',
    messagingSenderId: '453820398714',
    projectId: 'skydreamer-skywalker',
    storageBucket: 'skydreamer-skywalker.firebasestorage.app',
    iosBundleId: 'com.skydreamers.GoMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApBbN5M8u77tvgRkKKrEP5-SziQb0CEOM',
    appId: '1:453820398714:ios:dc5ee797a5792cf9a1cfc3',
    messagingSenderId: '453820398714',
    projectId: 'skydreamer-skywalker',
    storageBucket: 'skydreamer-skywalker.firebasestorage.app',
    iosBundleId: 'com.example.gomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZEyspaFb4swXkxvoM1MRJPv-7TRX8A0o',
    appId: '1:453820398714:web:5f6dbd5759eb1ecda1cfc3',
    messagingSenderId: '453820398714',
    projectId: 'skydreamer-skywalker',
    authDomain: 'skydreamer-skywalker.firebaseapp.com',
    storageBucket: 'skydreamer-skywalker.firebasestorage.app',
  );
}
